name: Update GitHub Profile

on:
  push:
    branches:
      - main

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Working Directory
        run: |
          git status

      - name: Commit and Push Changes
        run: |
          git config user.name 'Nileshchakradhar'
          git config user.email 'nileshchakradhar@gmail.com'
          git add .
          git commit -m 'Update GitHub profile'
          git push
